default: &default
  adapter: postgresql
  pool: <%= ENV['PUMA_THREADS'] || 10 %>
  timeout: 5000

development:
  <<: *default
  port: 5432
  database: link
  username: link
  password: link

test:
  <<: *default
  database: link_test

production:
  <<: *default
